---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: envoy-whitelist
  namespace: ambassador
spec:
  External:
    auth_service: envoy-whitelist:10000

---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: envoy-whitelist
  namespace: ambassador
spec:
  rules:
  - host: "*"
    path: "*"
    filters:
    - name: envoy-whitelist